### ISSUE TITLE
Encoding Problem.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#19]
Momentan sind unsere Quellcodedateien in UTF-8 encodiert, was meiner Meinung nach auch sehr gut so ist. Die Indexseite der Webapp ist derzeit HTML4, was als Default-Encoding nicht UTF-8 hat, sondern ISO-8859-1 iirc. Daher kommt es bei der Darstellung einiger Sonderzeichen zu Fehlern.

Man könnte dies beheben, indem man mittels eines `meta-Tags` explizit UTF-8 als Character Encoding angibt. Ich würde allerdings eher vorschlagen, dass wir lieber HTML5 verwenden, da in HTML5 UTF-8 das Default-Encoding ist (durch Bootstrap nutzen wir eh schon massenweise CSS3, außerdem ist es aktueller Standard).

Die Datei `files.php`, die den Dateimanager beinhaltet ist bereits in HTML5 geschrieben (durch `header.php` ist das Grundgerüst inkludiert).
![bildschirmfoto 2015-03-30 um 21 17 40](https://cloud.githubusercontent.com/assets/5717791/6904709/1828beac-d723-11e4-854e-4e258443b96d.png)

**Comment by llgb** [comment]
Stimmt, das sieht in der Tat unschön aus.
Werde das ändern sobald das Carousel fertig ist.

**Comment by llgb** [comment]
afaik müsste der Doctype  **<!DOCTYPE html>**  welcher in der header.php steht html5 deklarieren. 
(Außerdem ist im meta-Tag das encoding auf UTF8 gesetzt)

Beim Aufruf von index.php?page=basis erscheinen Umlaute trotzdem falsch kodiert.
Wie wollen wir weiter vorgehen? Umlaute als Entitäten ein-/ausgeben oder hast du eine andere Idee wie man das den Browser korrekt interpretieren lässt?

**Comment by llgb** [comment]
Hat sich erledigt, der Code in der index.php war noch etwas unsauber bzw hatte doppelte Deklarationen :sweat_smile: 

fixed with 9981cfb91d0a7e70568e6af44492981a3022554e
