### ISSUE TITLE
imagelist.php ein Verzeichnis höher schieben

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#21]
`imagelist.php` enthält keine Klasse, daher sollte es auch nicht im Verzeichnis `classes` liegen, sondern eine Hierarchie höher, direkt im Verzeichnis `www`.

**Comment by llgb** [comment]
ok das ist nachvollziehbar. Hatte beim Erstellen den Sinn des Classes-Ordner falsch interpretiert ;-)

fixed with commit:
c3738a817ba8a9e4068cd3d2039962b067f2678f
