### ISSUE TITLE
Menüpunkte in eigene PHP-Dateien auslagern.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#22]
Verschiedene Seiten wie beispielsweise die Gallerie werden über die `index.php` Datei und einen GET-Parameter adressiert. Der Grund dafür ist mir nicht wirklich klar. Man sollte sie in eigene Dateien auslagern, so dass man beispielsweise über `GET /gallery.php` die Gallerieseite bekommt.

**Comment by llgb** [comment]
Der ursprüngliche Grund heirfür war, dass man die zentrale Index-Seite als Rahmenkonstrukt (inkludiert Header, navigation, Content und Footer/skripte) nutzt und nur nach Bedarf die importierten Inhaltsseiten im Content-Bereich austauscht.
Würden wir für jeden Menüpunkt eigene "vollständige" php seiten erstellen, dann wären sich diese abgesehen vom eigentlichen Inhalt identisch (Zuerst includes von Header&navigation, dann der individuelle Content und anschließend include von footer/skripte)

**Comment by llgb** [comment]
fixed with commit 422ba7c0e45d3bc8899beb08958c9a2737a87bd0
