### ISSUE TITLE
Javascript Code der Gallerie sollte in Datei ausgelagert und inkludiert werden.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#23]
Der Javascript Code ist in einem _script-Tag_ direkt im HTML-Dokument. Generell sollte Javascript Code aber besser in einer eigenen Javascript-Datei liegen, welche dann in der Seite inkludiert wird.

Da bei der Gallerie `$(document).ready()` Funktionen aufgerufen werden, die spezifisch für die Gallerie sind, sollte der Javascript Code nicht in die allgemeine Javascript-Datei `epr-crc.js`, sondern in eine weitere Datei ausgelagert werden, beispielsweise `gallery.js` o.Ä.

**Comment by llgb** [comment]
absolut korrekt! War vorher unsauber und noch vom entwickeln&testen nicht geändert.

fixed with commit:
9c8a59000b1bdadd57ee276644107064bdc50f2a
