### ISSUE TITLE
Hervorhebung des aktiven Tabs im Menü durch Variable

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#24]
Eine Variable, welche im jeweiligen Haupttemplate gestetzt wird, soll im Navigationstemplate abgefragt werden und den entsprechenden Tab hervorheben.

Dies wäre sauberer, als jeweils GET-Parameter abzufragen oder die URL zu analysieren.

**Comment by llgb** [comment]
fixed with commit b639b06d4050dc8b7494a37f58cf2b6332d7d221
