### ISSUE TITLE
Dateimanager: Sortierreihenfolge ändern -> nach Typ

### ISSUE THREAD

**Issue by llgb** [StudA-EPR/EPR-CRC#25]
Aus Gründen der Intuitivität wäre es für Endanwender angenehmer, wenn im Dateimanager zuerst alle Ordner und anschließend erst alle Dateien eines Verzeichnisses gelistet werden. Aktuell werden die Einträge alphabetisch sortiert.

**Comment by nsommer** [comment]
Duplikat von #11.

**Comment by nsommer** [comment]
Wird aus Zeitgründen nicht implementiert.
