### ISSUE TITLE
Übertrage thumbnail eines Schnappschusses statt des volaufgelösten Bilds.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#27]
# Aktuelle Situation

Wenn ein Schnappschuss gemacht wird, wird derzeit das vollaufgelöste Bild, welches mehrere Megapixel groß ist (je nach Kamera) übertragen. Das ist natürlich nicht sinnvoll, da der Bereich im WEB UI, in dem das Bild dann angezeigt wird, nur ein Bruchteil der Pixelfläche groß ist.
# Soll-Situation

Daher wäre es sinnvoll, nach dem Herunterladen der Bilddatei von der Kamera ein Thumbnail - bspw. mit 720x576px o.Ä. - zu erzeugen und dieses dann anstatt des Originalbildes im UI anzuzeigen. Selbstverständlich wäre im UI ein einstrechender Button o.Ä. nötig, mit welchem sich auf Nutzerwunsch auch noch das Originalbild in voller Auflösung nachladen ließe.
# Technische Implementierung

Zur Generierung der Thumbnaildatei könnte `imagemagick` verwendet werden. Die Thumbnaildatei muss immer nur für den aktuellen Schnappschuss gespeichert werden, d.h. der nächste Schnappschuss würde seine Thumbnaildatei über die alte schreiben.

Auf PHP Seite existiert bereits ein leerer Methodenrumpf in der Klasse `GPhoto` namens `captureImageAndPreview()`. Dieser sollte ein Array zurückgeben, welches die Dateinamen der Originalbilddatei und der Thumbnaildatei enthält.

Die Datei `snapshot.php`, welche asynchron aufgerufen wird um einen Schnappschuss auszulösen, sollte dann mit dem GET-Parameter `preview=true` aufgerufen werden um die Thumbnailgenerierung zu initiieren. Die JSON-Datei, die zurückgeliefert wird, müsste entsptrechend auch den Dateinamen der Thumbnaildatei enthalten.

**Comment by nsommer** [comment]
**Cooler Einfall**: Theoretisch könnte man die Auflösung des zu generierenden Thumbnails sogar dynamisch beim AJAX-Call mitgeben, in dem man die Bildschirmgröße berücksichtigt. Stickwort `Responsive Images`.

Aber das haut zeitlich wohl nicht mehr hin ...

**Comment by nsommer** [comment]
Die für imagemagick benötigten Pakete bei OpenWrt heißen `imagemagick`, `imagemagick-jpeg` und `imagemagick-tools`.

Leider sind diese Pakete unvollständig, was auch schon länger bekannt ist. Siehe [Foreneintrag](https://forum.openwrt.org/viewtopic.php?id=46769). Die Datei `delegates.xml` scheint zu fehlen.

``` sh
root@OpenWrt:/www/photos# convert "image_2015-04-09\ 18\:06\:05.jpg" -resize 600
x400 thumbnail.jpg
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/591.
convert: NoDecodeDelegateForThisImageFormat `06\:05.jpg' @ error/constitute.c/ReadImage/544.
convert: NoImagesDefined `thumbnail.jpg' @ error/convert.c/ConvertImageCommand/3044.
```

Das die Datei `delegates.xml`nicht installiert wurde, kann man der leeren Ausgabe von `find / -name delegates.xml` entnehmen.

**Comment by nsommer** [comment]
Ich habe die Date [heruntergeladen](http://www.imagemagick.org/source/delegates.xml) und in `/etc` abgelegt, imagemagick beschwert sich nun, die Datei nicht öffnen zu können (ausgeführt mit root Rechten).

``` bash
root@OpenWrt:/www/photos# convert "image_2015-04-09\ 18\:06\:05.jpg" -resize 600
x400 thumbnail.jpg
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/591.
convert: NoDecodeDelegateForThisImageFormat `06\:05.jpg' @ error/constitute.c/ReadImage/544.
convert: NoImagesDefined `thumbnail.jpg' @ error/convert.c/ConvertImageCommand/3044.
```

**Comment by llgb** [comment]
oh man das ist ja herrlich -.-
so wie es sich in dem verlinkten  Foreneintrag liest, haben es die User tmo26 und Beef Eater hinbekommen in dem sie es selbst compiled haben. 
Schade, dass die ihre Pakete nicht zur Verfügung gestellt haben (so wie die reparierten gphoto Pakete anderer User).

**Comment by nsommer** [comment]
Jap, selbst kompilieren könnte man probieren. Muss aber sagen, dass ich da aktuell wenig Motivation habe. Ich glaube einer hat sogar seine Paketdateien geteilt, aber für eine andere Prozessorarchitektur ...

Ich würde vorschlagen das Thumbnail generieren vorerst auf Eis zu legen.

**Comment by llgb** [comment]
boah ne selber compilieren muss aktuell echt nicht sein. Würde auch sagen dass wir das dann auf Eis legen.
