### ISSUE TITLE
Bildergalerie sollte zum ersten Bild zurückspringen, wenn alle Bilder geladen wurden.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#28]
Ich habe 5 Bilder auf dem Router. Wenn ich beim 5. Bild in der Galerie bin und den rechten Pfeil klicke, kommt kurz das Popup-Fenster zum Laden der nächsten 5 Bilder, die es ja aber bei mir nicht gibt.

Stattdessen sollte eine Fehlerbehandlung eingebaut werden, die vor dem Nachladen prüft, ob überhaupt noch weitere Bilder da sind. Wenn nicht, sollte der rechte Pfeil dazu führen, dass die Bildergalerie wieder zum ersten Bild zurückspringt.

**Comment by llgb** [comment]
> Stattdessen sollte eine Fehlerbehandlung eingebaut werden, die vor dem Nachladen prüft, ob überhaupt noch weitere Bilder da sind. Wenn nicht, sollte der rechte Pfeil dazu führen, dass die Bildergalerie wieder zum ersten Bild zurückspringt.
> Das Zurückspringen macht der rechte Pfeil beim Carousel per default schon. Fehlerbehandlung wurde jetzt noch nachgerüstet.
> 
> Ich habe 5 Bilder auf dem Router. Wenn ich beim 5. Bild in der Galerie bin und den rechten Pfeil klicke, kommt kurz das Popup-Fenster zum Laden der nächsten 5 Bilder, die es ja aber bei mir nicht gibt.
> geht jetzt auch :)

fixed with 1db3cb4c725c6049d7330f5e342ba5f132b207c9
