### ISSUE TITLE
Bildergalerie sollte kein Carousel anzeigen, wenn es gar keine Bilder gibt.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#29]
Man könnte dann einen Hilfstext anzeigen, der sagt, dass es noch keine Bilder gibt und wo man welche machen kann.

**Comment by llgb** [comment]
erledigt mit 98cf705796ba08a3b2cdc7c6b51a91fa620d7bb8 (und in gewisser weise auch mit  7f65746493df9a9b671476dbf6b1ac751d1f0408 :sweat_smile: )
