### ISSUE TITLE
Mögliche extended-Einstellmöglichkeiten

### ISSUE THREAD

**Issue by llgb** [StudA-EPR/EPR-CRC#31]
Hier können die, von uns angebotenen, Kameraeinstellmöglichkeiten und dazugehörige gphoto Parameter gesammelt und diskutiert werden.

| Einstellmöglichkeit | Umsetzung bei Gphoto | Frage/to discuss |
| --- | --- | --- |
| Verschlusszeit | `gphoto2 --set-config-value /main/capturesettings/shutterspeed2=1/3200` |  |
| Blende | `gphoto2 --set-config-value /main/capturesettings/f-number=f/9` |  |
| ISO (LIchtempfindlichkeit) | `gphoto2 --set-config /main/imgsettings/iso` allerdings muss noch geprüft werden ob die ISO Automatik ausgeschaltet ist `gphoto2 --get-config /main/imgsettings/isoauto` (falls nein, muss man diese selbst ausschalten) |  |
| Serienaufnahmen | anscheinend kein spezieller Befehl vorhanden ? --> for-Schleife |  |
| Intervall | `gphoto2 --interval SECONDS` | soll diese Funktionalität ohne eine Anzahl Frames angeboten werden? Wie wird die Intervallaufnahme dann abgebrochen/beendet? |
| Akku-Stand | `gphoto2 --get-config /main/status/batterylevel` | eventuell auch prüfen ob `/main/status/externalpower` angeschlossen ist |

Da github pro issue nur eine Person zuweisen kann, werden wir beide hier so markiert:
@nsommer  @llgb

**Comment by nsommer** [comment]
Was zu u.A. zu klären wäre: Sind die Einstellungen, wenn sie geändert/gesetzt sind **persistent**? D.h. muss man sie neu setzen, wenn die Kamera an/aus geschaltet bzw. ab/an gestöpselt wird? Das hätte nämlich zur Folge, dass die App die Einstellungen speichern müsste (z.b. in einer Textdatei) um sie beim nächsten mal zu überprüfen und ggf. neu zu setzen.

**Comment by nsommer** [comment]
Auch definieren sollten wir, da wir ja - wie bereits besprochen - überprüfen wollen welche Funktionen die Kamera unterstützt und dementsprechend UI-Elemente ausgrauen wollen, ob wir grundsätzlich nur für **den Use Case einer einzigen Kamera** planen wollen, oder ob wir die Einstellungen speichern und an die verwendete Kamera "koppeln" wollen, so dass man mehrere Kameras nacheinander anschließen könnte (nicht parallel) und jede ihre eigenen Einstellungen hätte.

Ich wäre dafür, nur für das Szenario _eine einzige Kamera_ zu planen, da wir diesbezüglich keine Vorgaben erhalten haben und es zusätzlichen Aufwand bedeuten würde.

**Comment by nsommer** [comment]
# Diskussion Intervallaufnahme

**Abbruch**: Hier wäre ich dafür, beim Start der Intervallaufnahme eine Abbruchbedingung explizit zu definieren (durch UI Eingabe), beispielsweise die Anzahl der Bilder oder eine Zeitspanne.

**Anzahl der Frames**: Bin mir gerade nicht im klaren was das bedeutet, kannst du das näher erklären?

**Comment by nsommer** [comment]
# Diskussion Akku-Stand

Prüfen, ob die Stromquelle angeschlossen ist, fände ich super!

**Comment by llgb** [comment]
> Ich wäre dafür, nur für das Szenario eine einzige Kamera zu planen, da wir diesbezüglich keine Vorgaben erhalten haben und es zusätzlichen Aufwand bedeuten würde.

das können wir gerne machen. Zur Abfrage was möglich ist:
mit `gphoto --list-config` bekommt man alle möglichen Parameter der angeschlossenen Kamera zurückgeliefert.
Ruft man nun mit `gphoto2 --get-config EINTRAG` die aktuellen Einstellungen eines gewünschten Eintrages auf, so erhält man eine Rückmeldung über den aktuellen Stand, welche sich gut als JSON Objekt eignet.

Eventuell macht es auch Sinn, über alle Einträge des `--get-config` drüber zu iterieren und bei jedem die aktuellen Werte abzufragen. Die Abfrage liefert darüber hinaus zurück, welche Werte an sich möglich sind.

**Comment by llgb** [comment]
> Was zu u.A. zu klären wäre: Sind die Einstellungen, wenn sie geändert/gesetzt sind persistent? D.h. muss man sie neu setzen, wenn die Kamera an/aus geschaltet bzw. ab/an gestöpselt wird? 

Das kann ich direkt mal testen, ich denke dass die Einstellungen nur solange persistent sind, so lange die Kamera angeschlossen ist, gebe aber gleich nochmal Rückmeldung

**Comment by nsommer** [comment]
Auch interessant ist die Ausgabe von `gphoto2 --abilites`. Ist aber nicht so detailliert.

Ausgabe für unsere Referenzkamera (S3300):

``` bash
root@OpenWrt:~# gphoto2 --abilities
Abilities for camera             : Nikon Coolpix S3300 (PTP mode)              
Serial port support              : no
USB support                      : yes
Capture choices                  :
                                 : Image
Configuration support            : yes
Delete selected files on camera  : yes
Delete all files on camera       : no
File preview (thumbnail) support : yes
File upload support              : yes
```

**EDIT**: Wobei die Angaben mit Vorsicht zu genießen sind. Das löschen einzelner Bilder geht ja trotz gegenteiliger Angabe nicht bei mir. Kann aber auch am Treiber/der gphoto Version liegen, ich hab da einige komische Fehlermeldungen.

**EDIT2**: Ausgabe von `gphoto2 --list-config` auf der Referenzkamera:

``` bash
root@OpenWrt:~# gphoto2 --list-config
/main/settings/datetime                                                        
/main/settings/fastfs
/main/settings/capturetarget
/main/status/serialnumber
/main/status/manufacturer
/main/status/cameramodel
/main/status/deviceversion
/main/status/vendorextension
/main/capturesettings/flashmode
/main/capturesettings/focallength
/main/capturesettings/focusmode
/main/wifiprofiles/new/name
/main/wifiprofiles/new/essid
/main/wifiprofiles/new/ipaddr
/main/wifiprofiles/new/netmask
/main/wifiprofiles/new/gw
/main/wifiprofiles/new/accessmode
/main/wifiprofiles/new/channel
/main/wifiprofiles/new/encryption
/main/wifiprofiles/new/key
/main/wifiprofiles/new/write
/main/other/d407
/main/other/d406
/main/other/d002
/main/other/5011
/main/other/500c
/main/other/500a
/main/other/5008
/main/other/5001
/main/other/d303
```

**Comment by llgb** [comment]
> **Abbruch**: Hier wäre ich dafür, beim Start der Intervallaufnahme eine Abbruchbedingung explizit zu definieren (durch UI Eingabe), beispielsweise die Anzahl der Bilder oder eine Zeitspanne.
> **Anzahl** der Frames: Bin mir gerade nicht im klaren was das bedeutet, kannst du das näher erklären?

Mit Anzahl der Frames meine ich das, was du man mit "anzahl der Bilder" meinst.
Sprich: Man gibt an "erstelle alle X Sekunden ein Bild und mache dies so lange bis du Y Aufnahmen hast"
Fände ich eigentlich eine gute Lösung.
Die Zeit als Abbruch bedingung müssten wir dann per PHP mit der Systemzeit machen, oder?

**Comment by llgb** [comment]
Interessant wäre von der Referenzkamera noch die Ausgabe von `gphoto2 --list-config` 
Kannst Du die bitte auch noch anfügen?

**Comment by llgb** [comment]
# Diskussion Akku-Stand

> Prüfen, ob die Stromquelle angeschlossen ist, fände ich super!

Ok gut, ich denke wenn wir da ein JSON über die aktuelle Config haben können wir prüfen ob eine Stromquelle angeschlossen ist und sonst eben den Akkustand im UI anzeigen

**Comment by llgb** [comment]
Die Ausgabe von `gphoto2 --abilities` unterscheidet sich zu meiner DSLR nur in dem Punkt, dass ich noch `Preview`als Möglichkeit für die "Capture choices" habe

**Comment by nsommer** [comment]
> Die Zeit als Abbruch bedingung müssten wir dann per PHP mit der Systemzeit machen, oder?

So wie ich das sehe startet man einen Endlos-Intervallauftrag mit `--intervall <Intervallgröße in Sekunden>` und beendet diesen durch den Aufruf mit `--reset-intervall`.

Möchte man den Intervallauftrag nach einer gewissen Zeit beenden, wartet man im PHP durch einen synchronen sleep-Aufruf o.Ä. diese Zeit und sendet dann das reset-Signal.

Möchte man nach Anzahl der Bilder warten, berechnet man anhand der Intervalllänge und anhand der zu schießenden Bilder die benötigte Gesamtzeit, wartet solange im PHP und sendet dann (evtl. mit etwas Pufferzeit) das reset-Signal

**Comment by llgb** [comment]
# Diskussion: Einstellungen persistieren

Da wir die Kamera sozusagen im manuellen Modus betreiben, verhält sich das setzen der Einstellungen über gphoto2 so, als ob man dies von Hand an der Kamera tut.
Nach dem absetzen eines `gphoto2 --set-config-index ...` oder `gphoto2 --set-config-value ...` Befehls wird diese Einstellung in der Kamera eingestellt und auch dort gespeichert.
Somit also nicht unser Problem :)

**Comment by nsommer** [comment]
> Ok gut, ich denke wenn wir da ein JSON über die aktuelle Config haben können wir prüfen ob eine Stromquelle angeschlossen ist und sonst eben den Akkustand im UI anzeigen

Wie meinst du " da wir da ein JSON [..] haben"?

Den Akkustand abfragen dürfte ja eigentlich schnell gehen, sodass es nicht asynchron geschehen müsste und man eine entsprechende PHP Methode (am besten Wrapper bauen) einfach im UI-Template aufrufen kann.

**Comment by nsommer** [comment]
> Diskussion: Einstellungen persistieren
> 
> Da wir die Kamera sozusagen im manuellen Modus betreiben, verhält sich das setzen der Einstellungen über gphoto2 so, als ob man dies von Hand an der Kamera tut.
> Nach dem absetzen eines gphoto2 --set-config-index ... oder gphoto2 --set-config-value ... Befehls wird diese Einstellung in der Kamera eingestellt und auch dort gespeichert.
> Somit also nicht unser Problem :)

Super! Ich werde das nachher auch nochmal an der Referenzkamera ausprobieren ... Das sollte uns Arbeit sparen!

**Comment by llgb** [comment]
> So wie ich das sehe startet man einen Endlos-Intervallauftrag mit --intervall <Intervallgröße in Sekunden> und beendet diesen durch den Aufruf mit --reset-intervall.

Ok das wäre super. Mich haben die Infos in der manpage zu den Singalen während eines Intervalls etwas irritiert.

> Möchte man nach Anzahl der Bilder warten, berechnet man anhand der Intervalllänge und anhand der zu schießenden Bilder die benötigte Gesamtzeit, wartet solange im PHP und sendet dann (evtl. mit etwas Pufferzeit) das reset-Signal

Das ist afaik nicht notwendig, da gphoto nach Erreichen der angegebenen Bilder-Anzahl selbst abbricht.
Quelle:

> For simpler applications, you may not need a script at all: gphoto has a built-in time-lapse mode for occasions when the settings will stay the same through all exposures. This is easy to use, such as this example which takes a photo every 30 seconds. It goes for 120 frames and then stops.

`gphoto2 --interval=30 --frames=120 --capture-image-and-download`
Link: http://blog.dcclark.net/2012/04/automating-time-lapse-photos-with.html

**Comment by nsommer** [comment]
> Das ist afaik nicht notwendig, da gphoto nach Erreichen der angegebenen Bilder-Anzahl selbst abbricht.
> Quelle:
> 
> For simpler applications, you may not need a script at all: gphoto has a built-in time-lapse mode for occasions when the settings will stay the same through all exposures. This is easy to use, such as this example which takes a photo every 30 seconds. It goes for 120 frames and then stops.
> gphoto2 --interval=30 --frames=120 --capture-image-and-download
> Link: http://blog.dcclark.net/2012/04/automating-time-lapse-photos-with.html

Ah, ok. Ich war mir der Option `--frames` nicht bewusst, umso besser!

**Comment by llgb** [comment]
> Wie meinst du " da wir da ein JSON [..] haben"?
> 
> Den Akkustand abfragen dürfte ja eigentlich schnell gehen, sodass es nicht asynchron geschehen müsste und man eine entsprechende PHP Methode (am besten Wrapper bauen) einfach im UI-Template aufrufen kann.

Ok gerne das wäre natürlich auch super. 
Ich dachte jetzt dass die extended.php beim Aufruf zuallererst die `--list-config`einliest, bei jedem Eintrag `--get-config EINTRAG` durchführt und uns daraus einen großen JSON String zurückliefert mit dem wir dann weiterarbeiten und den Inhalt der Seite aufbauen können.

Aber stimmt direkt im UI oben rechts wäre super und geht von der Aufruf-Dauer auch gut :)

**Comment by nsommer** [comment]
> Ich dachte jetzt dass die extended.php beim Aufruf zuallererst die --list-configeinliest, bei jedem Eintrag --get-config EINTRAG durchführt und uns daraus einen großen JSON String zurückliefert mit dem wir >dann weiterarbeiten und den Inhalt der Seite aufbauen können.
> 
> Aber stimmt direkt im UI oben rechts wäre super und geht von der Aufruf-Dauer auch gut :)

Ich denke es wird sich zeigen, wie schnell die ganzen Abfragen sein werden. Sollte es wider Erwarten doch spürbare Requestzeiten geben, kann man das immer noch recht schnell auf einen asynchronen AJAX-Request mit JSON-Datei umstellen.

Was wir wo im UI anzeigen, ist vorerste denk ich von sekundärer Bedeutung. Wenn die Funktionalität dann da ist, kann man das ja immer noch mit wenigen Handgriffen im UI hin und her schieben ;-).

**Comment by nsommer** [comment]
Ich habe soeben ein paar Methoden implementiert, mit der alle Konfigurationsoptionen ausgelesen werden können.

**Erste Beobachtung:**
Die Ausführung auf dem Router dauert gefühlt _5-10 Sekunden_. Eventuell sollte das später doch asynchron über AJAX-Requests abgefragt werden (vielleicht sogar mit einem AJAX-Request pro Konfigurationsoption, so dass im UI nach und nach die einzelnen Optionen aktiv werden). Das aber erst, wenn grundsätzlich alles klappt.

**Zweite Beobachtung:**
Zur Referenzkamera kommen genau 131 Zeilen Ausgabe zurück. Ich bin so frei die mal hier aufzulisten.

``` bash
Label: Camera Date and Time
Type: DATE
Current: 1428943499
Printable: Mon Apr 13 18:44:59 2015
Label: Fast Filesystem
Type: TOGGLE
Current: 1
Label: Capture Target
Type: RADIO
Current: Internal RAM
Choice: 0 Internal RAM
Choice: 1 Memory card
Label: Serial Number
Type: TEXT
Current: None
Label: Camera Manufacturer
Type: TEXT
Current: Nikon Corporation
Label: Camera Model
Type: TEXT
Current: S3300
Label: Device Version
Type: TEXT
Current: COOLPIX S3300 V1.0
Label: Vendor Extension
Type: TEXT
Current: microsoft.com: 1.0;
Label: Flash Mode
Type: RADIO
Current: Automatic Flash
Choice: 0 Automatic Flash
Choice: 1 Flash off
Choice: 2 Fill flash
Choice: 3 Red-eye automatic
Label: Focal Length
Type: RANGE
Current: 35
Bottom: 35
Top: 105
Step: 1
Label: Focus Mode
Type: RADIO
Current: Automatic
Choice: 0 Automatic
Choice: 1 Automatic Macro
Label: Profile name
Type: TEXT
Current:
Label: WIFI ESSID
Type: TEXT
Current:
Label: IP address (empty for DHCP)
Type: TEXT
Current:
Label: Network mask
Type: TEXT
Current:
Label: Default gateway
Type: TEXT
Current:
Label: Access mode
Type: RADIO
Current: Managed
Choice: 0 Managed
Choice: 1 Ad-hoc
Label: WIFI channel
Type: RANGE
Current: 1
Bottom: 1
Top: 11
Step: 1
Label: Encryption
Type: RADIO
Current: None
Choice: 0 None
Choice: 1 WEP 64-bit
Choice: 2 WEP 128-bit
Label: Encryption key (hex)
Type: TEXT
Current:
Label: Write
Type: TOGGLE
Current: 0
Label: PTP Property 0xd407
Type: TEXT
Current: 1
Label: PTP Property 0xd406
Type: TEXT
Current:
Label: PTP Property 0xd002
Type: MENU
Current: 6
Choice: 0 1
Choice: 1 2
Choice: 2 3
Choice: 3 4
Choice: 4 5
Choice: 5 6
Choice: 6 7
Label: Date & Time
Type: TEXT
Current: 20150413T174522
Label: Flash Mode
Type: MENU
Current: 1
Choice: 0 1
Choice: 1 2
Choice: 2 3
Choice: 3 4
Label: Focus Mode
Type: MENU
Current: 2
Choice: 0 2
Choice: 1 3
Label: Focal Length
Type: MENU
Current: 3500
Choice: 0 3500
Choice: 1 4600
Choice: 2 5300
Choice: 3 6100
Choice: 4 7300
Choice: 5 8600
Choice: 6 10500
Label: Battery Level
Type: MENU
Current: 100
Choice: 0 2
Choice: 1 5
Choice: 2 25
Choice: 3 50
Choice: 4 65
Choice: 5 80
Choice: 6 100
Label: PTP Property 0xd303
Type: TEXT
Current: 1
```

Was man jetzt machen muss, ist diese Ausgaben zu parsen und heraus zu lesen, welche Einstellungen denn nun existieren bzw. wie einstellbar sind.

Ich plane hierfür eine Klasse `Settings` o.Ä. welche aus dem UI-Template leicht zu verwenden ist und beim initialisieren (Konstruktur) das Parsing vornimmt.

**EDIT**:
Hier mal noch das Testprogramm, das die Methoden (die momentan lediglich gphoto Aufrufe wrappen) aufruft und im Browser ausgibt.

``` php
require_once 'classes/gphoto.php';
date_default_timezone_set('UTC');

try {
    $configs = GPhoto::listConfig();

    foreach ($configs as &$config) {
        $configDetails = GPhoto::getConfig($config);

        foreach ($configDetails as &$line) {
            echo $line . '<br />';
        }
    }

} catch (GPhotoException $e) {
    echo $e->getMessage() . PHP_EOL;
}
```

**Comment by llgb** [comment]
> **EDIT:**
> Hier mal noch das Testprogramm, das die Methoden (die momentan lediglich gphoto Aufrufe wrappen) aufruft und im Browser ausgibt.

`Warning: Invalid argument supplied for foreach() in /www/extended.php on line 123`

Hat das bei Dir mit dem Testprogrammaufruf funktioniert? var_dump($configs); geht bei mir, die foreach Schleife kann jedoch nicht ausgeführt werden, da sie einen Array benötigt und aktuell noch einen String erhält.

**Comment by nsommer** [comment]
Ich hab doch noch nix eingecheckt :D

**Comment by llgb** [comment]
> Ich hab doch noch nix eingecheckt :D

:D dachte das Beispielprogramm basiert auf dem was bisher schon in der gphoto.php stand :D aber dann warte ich noch geduldig ab ;D

**Comment by nsommer** [comment]
Mit dem commit 720536903448e8f86106273ff9d996a315e2341b wurde eine Abstraktionsschicht für die Konfigurationseinstellungen in Form einer objektorientierten API hinzugefügt.

**Die Option Klasse**:
Die `Option` Klasse repräsentiert eine einzelne Konfigurationsoption, wie sie mittels `gphoto --get-config <descriptor>` abgefragt werden kann.

**Die Settings Klasse**:
Die `Settings` Klasse sammelt alle möglichen Konfigurationsoptionen. Bei der Instanziierung fragt sie über `gphoto --list-config` die möglichen Konfigurationsoptionen ab und instanziiert für jede Konfigurationsoption ein `Option` Objekt, welches die mit `gphoto --get-config <descriptor>` erhaltenen Details speichert.

**Performance**:
Man kann bereits durch den Konsolenaufruf von `gphoto --get-config <descriptor` eine spürbare Verzögerung beobachten. Diese Verzögerung summiert sich beim Abfragen aller vorhandenen Konfigurationsoptionen natürlich. Auf meinem Router beträgt die Zeit, die dafür benötigt wird ca. 5-10Sekunden.

**Verwendung**:
Das API kann entweder verwendet werden, in dem ganz einfach eine Instanz der `Settings` Klasse erzeugt wird. Deren API lässt sich am einfachsten durch einen Blick in den Quellcode erklären, die Methoden sind alle dokumentiert.

Hierzu ein einfaches Codebeispiel für den Browser:

``` php
<?php

require_once 'classes/settings.php';
require_once 'classes/htmlutils.php';
date_default_timezone_set('UTC');

try {
    $settings = new Settings();
    $options = $settings->getOptions();

    foreach ($options as &$option) {
        $optionSummary = $option->toString();
        echo HTMLUtils::convertNewlines($optionSummary) . PHP_EOL;
        echo '<br /><br />' . PHP_EOL;
    }

} catch (GPhotoException $e) {
    echo $e->getMessage() . PHP_EOL;
}
```

**Status**:
Die API scheint bei mir stabil zu funktionieren. Sie bietet momentan jedoch lediglich **lesenden Zugriff** auf die Konfiguration.

**Comment by nsommer** [comment]
Mit commit 505d245db5597ef1e1e0300531a9ba5679349cc6 wurde die Datei `settings-json.php` hinzugefügt. Ein simpler _GET Request` darauf liefert eine *_JSON-Datei*\* zurück, welche alle Konfigurationsoptionen beinhaltet.

Bei der Verarbeitung dieser JSON-Datei wird immer ein JSON-Objekt enthalten sein, welches einen `boolean`-Wert für das Feld `error` enthält. Ist dieser `false`, kann einfach das JSON-Array `settings` weiterverarbeitet werden. Ist dieser aber `true`, ging etwas schief. Dann gibt es kein JSON-Array `settings` sondern einige Felder, die Informationen über den Fehler (der GPhotoException) enthalten.

Dies ist etwas anschaulicher auch im Quellcode von `settings-json.php` ersichtlich.

**Comment by llgb** [comment]
Ich hab jetzt ewig mit Instanzen der Settings-Klasse rum versucht und hab sogar extra noch die IntelliJ Ultimate Edition IDE installiert, nen lokalen php Interpreter dafür eingerichtet (sinnlos :D ) und immernoch hat die extended.php mit verschiedenen Ausgaben des getOptions() Arrays nicht funktioniert, beziehungsweise sie hat den PHP-Teil bis zum timeout geladen/ausgeführt ohne Rückmeldung.

Um Fehler in meinem Code auszuschließen hab ich jetzt mal die settings-json.php aufgerufen und erhalte den Output:

> {"error":true,"message":"The execution of `gphoto2 --list-config` failed.","exitCode":139,"output":""}

genau dieser Befehl funktioniert aber auf der Konsole. Gibt es irgendeinen Punkt den ich übersehe ?

Beim erneuten Ausführen erhalte ich auch den `The CGI process did not produce any response` Fehler 

Dieser kommt nun ständig, bis auf ein mal, da kam noch die Meldung:

> {"error":true,"message":"The execution of `gphoto2 --get-config \/main\/actions\/manualfocusdrive` failed.","exitCode":139,"output":""}

Das würde ja bedeuten, dass er immerhin die Einträge der Settings laden konnte. reproduzieren konnte ich das allerdings nicht. Die restlichen Male kam nur noch der CGI-Fehler.

**Comment by nsommer** [comment]
> Beim erneuten Ausführen erhalte ich auch den The CGI process did not produce any response Fehler

Hatte ich auch anfangs ein einziges mal, konnte ich jedoch nicht reproduzieren. Ich tippe darauf, dass die Timeout-Zeit überschritten wird und der HTTP-Server dann denkt, es käme keine Antwort mehr. Man müsste sich mal die Einstellungen diesbezüglich in der `uhttpd.conf` ansehen.

> {"error":true,"message":"The execution of gphoto2 --list-config failed.","exitCode":139,"output":""}

Erstes googlen ergibt, dass es sich um einen bösen Speicherfehler handeln könnte (verwunderlich bei einer Sprache wie PHP mit Garbage Collection etc.).

Ich könnte mir vorstellen, dass auf dem Router der sehr begrenzte Arbeitsspeicher möglicherweise nicht ausreicht und der PHP Interpreter nicht mehr RAM vom Kernel bekommt und deshalb das gphoto Kommando einen Speicherfehler erzeugt.

Um dem auf den Grund zu gehen, habe ich soeben im Commit be41084a95d776e0e8991ceb19966155646a66d3 das Shellskript `mem-stat.sh` hinzugefügt. Dieses kann wie folgt aufgerufen werden.

``` bash
./mem-stat.sh <sekunden>
```

Dieses kann nun im PHP Code vor dem Instanziieren einer `Settings`-Klasse aufgerufen werden (beispielsweise mit 20 oder 30 Sekunden als Argument) und logt dann in eine Textdatei den Speicherverbrauch. Wichtig ist, dass das Skript im Hintergrund ausgeführt wird, damit das Speicher-Loggen und der zu untersuchende PHP-Code parallel laufen.

**EDIT**:
Das wäre wohl möglich, indem man das Skript so ausführt: `./mem-stat.sh <sekunden> > /dev/null 2>/dev/null &`. Dies würde die Ausgaben zu _/dev/null_ umleiten und die Ausführung in einen Hintergrundprozess verlagern.

**Comment by nsommer** [comment]
Durch einen _GET-Request_ auf die Datei `option-json.php` kann nun auch eine einzelne Option als JSON-Datei angefordert werden. Dies wurde im Commit ca6d73b31ac2b52d7c80f0604471aaf6ca30467d (Issue #34) implementiert.

**Beispiel:**
Um die aktuelle Konfiguration der Option `/main/capturesettings/flashmode` als JSON-Datei zu erhalten wird ein GET-Request mit dem Optionsdeskriptor als Value des Parameters `descriptor` ausgeführt. Die enkodierte URL eines solchen Request sähe wie folgt aus:

``` url
http://hostname/option-json.php?descriptor=%2Fmain%2Fcapturesettings%2Fflashmode
```

Die JSON-Datei sieht mit den Werkseinstellungen der Referenzkamera wie folgt aus:

``` json
{"option":"\/main\/capturesettings\/flashmode","label":"Flash Mode","type":"RADIO","current":"Automatic Flash","choices":["Automatic Flash","Flash off","Fill flash","Red-eye automatic"],"error":false}
```

**Comment by nsommer** [comment]
Wenn auch noch nicht mit mehreren Optionen per Request oder korrekter Fehlerbehandlung, ist es nun möglich mittlels eines GET Requests auf die Datei `change-option.php` eine Konfigurationsoption zu ändern. Im Folgenden die enkodierte URL um die Option `/main/capturesettings/flashmode` auf `Automatic Flash` zu setzen.

``` url
http://hostname/change-options.php?descriptor=%2Fmain%2Fcapturesettings%2Fflashmode&value=Automatic%20Flash
```

**Comment by llgb** [comment]
Es wäre super, wenn wir das setzen der Einstellungen über den index einer Option machen könnten, da ich dann direkt die Value-Werte der selectboxen an die verarbeitende PHP Datei weitergeben kann.

Beispiel:

> gphoto2 --set-config-index /main/capturesettings/shutterspeed=3

falls das aber vom Aufwand her zu groß ist könnte ich das ganze auch anders lösen. Sieht aber halt schöner aus :)

**Comment by nsommer** [comment]
> Es wäre super, wenn wir das setzen der Einstellungen über den index einer Option machen könnten, da ich dann direkt die Value-Werte der selectboxen an die verarbeitende PHP Datei weitergeben kann.

Ach das bedeutet der Indexwert :-D Ich hab die Möglichkeit den Indexwert zu setzen gesehen, aber nicht kapiert was das genau bedeutet ... Ich hatte mir gedacht, dass die `value` attribute der select Boxen den String der Optionsmöglichkeit (choice) beinhalten, dann könnte dieser auch direkt übergeben werden.

Es stimmt aber, dass das mit einer Indexzahl wesentlich sauberer wäre. Denn bei Strings als Value läuft man immer Gefahr Probleme mit _Non-ASCII Zeichen_ zu bekommen, wenn man nicht höllisch mit der Enkodierung aufpasst.

Ich werde auf PHP Seite im Laufe des Tages Funktionen einbauen, die auch mit Indexzahlen arbeiten können. Dementsprechend werde ich auch das `choices` Array in der Option-Klasse veranlassen zu jedem String (choice) die Indexzahl als Key zu speichern. Somit wird aus diesem Array eine Key-Value-Pair Sammlung, was auch im zurückgegeben JSON zu sehen sein wird.

**Comment by llgb** [comment]
> Es stimmt aber, dass das mit einer Indexzahl wesentlich sauberer wäre. [..]

jap auf jeden Fall. Wie gesagt per String wäre möglich, wollen wir aber nur ungern machen :)

> Dementsprechend werde ich auch das choices Array in der Option-Klasse veranlassen zu jedem String (choice) die Indexzahl als Key zu speichern. Somit wird aus diesem Array eine Key-Value-Pair Sammlung, was auch im zurückgegeben JSON zu sehen sein wird.

yeah perfekt Sobald es implementiert ist passe ich meinen Stand der extended an.

**Comment by nsommer** [comment]
Wir haben heute überlegt, alle Deskriptoren über `--list-config` abzufragen (asynchron) und dann hintereinander die einzelnen Optionen (ebenfalls asynchron) abzufragen und so nach und nach das extended UI aufzubauen.

Ich werde dies in einem seperaten branch machen.

**Comment by nsommer** [comment]
Ich habe ein Ablaufdiagramm erstellt, das nochmals verdeutlichen soll, wie die Einstellungen geladen werden sollen. Ich versuche das morgen oder so zu implementieren.

![Ablaufdiagramm Laden der Einstellungen](https://cloud.githubusercontent.com/assets/5717791/7257642/6dc13714-e857-11e4-9f9a-1f1240346a28.png)

**Comment by llgb** [comment]
Ok sehr gut. Implementierst Du dann in dem Zuge auch das dynamische erstellen der Selectboxen? 

Ich würde mich dann um #47 und #44 (wobei das recht schnell gehen sollte) kümmern und sonst noch weiter den Chat vorbereiten. (falls das nicht in deinem Sinne ist, bitte Bescheid geben ;) @nsommer )

**Comment by nsommer** [comment]
Passt ;-)
