### ISSUE TITLE
Löschen von Dateien funktioniert nicht

### ISSUE THREAD

**Issue by llgb** [StudA-EPR/EPR-CRC#32]
Wenn man im Dateimanager eine Datei löscht und den Abfrage-Dialog bestätigt, wird einem suggeriert, die Datei wäre gelöscht.
Navigiert man erneut in das Verzeichnis dieser Datei, so ist diese weiterhin vorhanen (getestet bei Bilder in /www/photos)

**Comment by nsommer** [comment]
Ich hatte in Erinnerung, dass es bei mir funktioniert, nachdem ich es gerade nochmal getestet habe, kriege ich aber auch einen Fehler.

``` php
Warning: unlink(/www/preview.jpg): No such file or directory in /www/classes/filemanager.php on line 45
```

**EDIT:**
Man sieht ja schon im Warning, dass er denkt die Datei läge direkt im `www` Verzeichnis, obwohl die Datei eine Ebene drunter im `photos` Verzeichnis liegt. Da geht wohl etwas in der Pfadauflösung schief, ich werde das korrigieren.
