### ISSUE TITLE
Ändern von Konfigurationsoptionen

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#35]
Derzeit können Konfigurationsoptionen über die Klasse `Option` nur gelesen werden. Die API soll um schreibende Methoden erweitert werden.

**Mögliche Vorangehensweise:**
- Hinzufügen von _Setter-Methoden_ in der Klasse `Option`.
- Hinzufügen einer Methode `public static function setConfig(Option $option)` in der Klasse `GPhoto`, welche ein Option-Objekt entgegennimmt und den Wert der Option mittels gphoto abändert.

**Integration in die Webanwendung:**

Hinzufügen eines PHP-Skripts, welches Parameter für Konfigurationsoptionen entgegennimmt und entsprechende Funktionen aufruft um die Optionen zu ändern. Anschließend sollte auf die Einstellungsseite weitergeleitet werden.

Subissue of #31

**Comment by nsommer** [comment]
Mit commit 9fba5237fd32be964ce54e1f4562f5c497220748 kamen die benötigten Methoden in den Klassen `Option` und `GPhoto`.

Mit commit a0b4df9702f84c518c6ef667108d852b422ac6cd kam ein Skript, dass _GET Parameter_ entgegennimmt und anhand dessen eine Option speichert. Wie in der Commit Message zu sehen fehlen noch einige Dinge, es ist jedoch bereits funktionstüchtig.

**Comment by nsommer** [comment]
Mit Commit 3a5fbab3f9605d5fb452954a80add2f6dbbd33bb wurde umgestellt auf JSON-Antworten anstatt auf die extended.php zu redirecten.

Lief alles glatt, ist die Antwort:

``` javascript
{"error":false}
```

Wenn nicht, ist der Wert von `error` true und die Details der `GPhotoException` werden wie gewohnt mitgeliefert.

**Comment by nsommer** [comment]
Über das Skript `change-options.php` ist es mittlerweile möglich Optionswerte zu ändern (sowohl über den Textwert als auch über die Indexzahl).

Mehrere Optionen auf einmal zu ändern (wie es der Plural im Dateinamen suggeriert) ist derzeit noch nicht möglich. Da der Aufruf des Skripts jedoch asynchron (AJAX) erfolgt und gphoto sowieso nur eine Option auf einmal ändern kann, gilt es festzulegen, ob das Skript denn überhaupt mehrere Optionswerte auf einmal entgegennehmen können müsste.

@llgb Kommentare hierzu?

**Comment by llgb** [comment]
> Da der Aufruf des Skripts jedoch asynchron (AJAX) erfolgt und gphoto sowieso nur eine Option auf einmal ändern kann, gilt es festzulegen, ob das Skript denn überhaupt mehrere Optionswerte auf einmal entgegennehmen können müsste.

Ok stimmt, das ist ein Argument. Wie bauen dir dann aber unsere Submit-Aktion für das Formular auf? Komplett mit Javascript? oder trotzdem ein großer Request mit mehreren GET-Parametern die dann von der change-options.php einfach der Reihe nach ausgeführt werden?

**Comment by nsommer** [comment]
Ich bin für ersteres. Ich schreibe gerade eine große Javascript Datei, die all das macht.

**Comment by llgb** [comment]
> Ich bin für ersteres. Ich schreibe gerade eine große Javascript Datei, die all das macht.

sehr gut! bin schon auf den Code gespannt.

**Comment by nsommer** [comment]
Zwecks Dokumentation eine kurze Erklärung, wie genau die Lösung aus Commit e43fcd26ff98e2b3aae343e6d6f29eb382d57d74 funktioniert:
Wird der Submit-Button gedrückt, sammelt eine JavaScript Funktion die Werte aller Input-Elemente (inkl. Checkboxen, Select-Boxen, etc.). Diese werden dann mit einem AJAX Request auf die Datei `change-options.php` an den Server übermittelt. Dieser schaut nach, welche der übermittelten Konfigurationswerte von den aktuell aktiven abweichen um die tatsächlichen zu ändernden Optionen zu ermitteln. Diese werden dann mittels gphoto geändert und ein Success/Fail Flag sowie die Anzahl der veränderten Optionen als JSON zurück zum Client gegeben.
