### ISSUE TITLE
Zusammenführung der Seiten Basis und Extended

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#36]
Die genannten Seiten sollten wie besprochen zusammengeführt werden. Innerhalb der Seite könnten die [Bootstrap-Tabs](http://getbootstrap.com/javascript/#tabs) verwendet werden um zu navigieren. Ich denke es wäre sinnvoll, den Code für die Einstellungen trotzdem in einer eigenen PHP-Datei zu belassen und diesen mittels `include` einzubinden, damit die Datei `index.php` nicht zu groß wird.

**Comment by llgb** [comment]
fixed with afed907e6cd6c77d3df12152c1f86aab38e684a9
