### ISSUE TITLE
Option, alle Fotos aus /www/photos als Archivdatei herunterzuladen

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#38]
Es wäre nett, wenn es eine Option gäbe _ondemand_ ein Archiv aller geschossenen Fotos zu generieren und herunterzuladen. Dies würde viel Aufwand ersparen, wenn alle Fotos heruntergeladen werden sollen und die Menge sehr groß ist.

Als Archivtyp würde sich `tar` eignen, da es sowieso schon auf jedem UNIX-System vorhanden ist. Außerdem ist ein tar Archiv an sich nicht komprimiert, was erstens signifikante Performanz kosten würde (auf der Routerhardware relevant) und zweitens aufgrund der JPEG-Komprimierung der Fotodateien sowieso keinen spürbaren Kompressionseffekt mehr erzielbar wäre.

**Mögliche Probleme:**
- Es könnte sein, dass nicht genügend Speicherplatz vorhanden ist um die Archivdatei temporär zwischenzuspeichern. Dies könnte überprüft werden, indem die Dateigröße aller Fotos summiert würde und mindestens die gleiche Anzahl Bytes noch im Dateisystem frei sein müsste.

**Comment by llgb** [comment]
Tipp:
Zum Erstellen würde sich die Funktion [PharData](http://php.net/manual/en/phardata.buildfromdirectory.php) eignen. Natürlich - wie Du bereits sagtest - nachem gecheckt wurde, ob genügen Speicherplatz vorhanden ist.

**Comment by nsommer** [comment]
Wird nicht implementiert, da Bearbeitungszeitraum der Studienarbeit beendet ist.
