### ISSUE TITLE
option.json.php liefert maximal 10 Einträge zurück

### ISSUE THREAD

**Issue by llgb** [StudA-EPR/EPR-CRC#39]
Beim Abfragen des Parameters **/main/capturesettings/shutterspeed** erhalte ich maximal 10 Einträge. Über die Konsole erhalte ich direkt über den Router jedoch 52 Choices

**Comment by nsommer** [comment]
Scheinbar hat deine Spiegelreflex deutlich mehr Optionen als unsere Nikon ... Habe auf Anhieb keine Idee woran es liegt, werde dem aber auf den Grund gehen. Bitte poste hier mal die Ausgabe der Konsole und die Ausgabe aus PHP oder JS.

**Comment by llgb** [comment]
ganz spontan hab ich ja `option.php: 69-80` im Verdacht.

Ausgabe der `/option-json.php?descriptor=%2Fmain%2Fcapturesettings%2Fshutterspeed2`

> {"option":"\/main\/capturesettings\/shutterspeed2","label":"Shutter Speed 2","type":"RADIO","current":"1\/80","choices":["1\/4000","1\/3200","1\/2500","1\/2000","1\/1600","1\/1250","1\/1000","1\/800","1\/640","1\/500"],"error":false}

Ausgabe der Konsole:

> root@OpenWrt:~# gphoto2 --get-config /main/capturesettings/shutterspeed2
> Label: Shutter Speed 2
> Type: RADIO
> Current: 1/80
> Choice: 0 1/4000
> Choice: 1 1/3200
> Choice: 2 1/2500
> Choice: 3 1/2000
> Choice: 4 1/1600
> Choice: 5 1/1250
> Choice: 6 1/1000
> Choice: 7 1/800
> Choice: 8 1/640
> Choice: 9 1/500
> Choice: 10 1/400
> Choice: 11 1/320
> Choice: 12 1/250
> [..]**aus Gründen der Übersichtlichkeit gekürzt**
> Choice: 49 20
> Choice: 50 25
> Choice: 51 30
> Choice: 52 65535/65535
> root@OpenWrt:~#
