### ISSUE TITLE
Deployment Skript für Windows 

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#4]
Wie #3 jedoch als Batch-Skript für Windows um auch unter Windows deployen zu können.

**Comment by nsommer** [comment]
#7 mit geringerer Priorität

**Comment by llgb** [comment]
Auf gleiche Art wie das Linux-Script umgesetzt.

**Comment by nsommer** [comment]
In der README.md Datei sollte die Verwendung des Skripts und die Nennung des Dateinamens eingefügt werden.

**Comment by llgb** [comment]
Mist, das hatte ich vergessen.
Hab's gefixt
