### ISSUE TITLE
Bei Auswahloptionen sollte der aktuelle Optionswert auch über die Indexzahl lesbar/änderbar sein.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#40]
Dies bezieht sich auf meinen Kommentar in Issue #31. Dies muss implementiert werden um Issue #35 zu schließen.

**Comment by llgb** [comment]
Wie meinst du das mit dem lesen?
Im aktuellen Stand wird bei der Abfrage der Kameraeinstellungen das Current-Feld der Einstellung geprüft und dementsprechend in der selectbox also ausgewählte Option gesetzt. Ist das ausreichend?

Ich denke der Issue hier bezieht sich nur auf das setzen mit Hilfe eines übermittelten Indexwerts, oder?

**Comment by nsommer** [comment]
Diesen Issue kannst du ignorieren, den hab ich mir nur gemacht um die Backendfunktionalität zu implementieren.

**Comment by nsommer** [comment]
Eine JSON Datei die die Informationen zu einer Option beinhaltet sieht nun so aus:

``` javascript
{
    "option": "\/main\/capturesettings\/flashmode",
    "label": "Flash Mode",
    "type": "RADIO",
    "current": "Automatic Flash",
    "choices": [
        [
            0,
            "Automatic Flash"
        ],
        [
            1,
            "Flash off"
        ],
        [
            2,
            "Fill flash"
        ],
        [
            3,
            "Red-eye automatic"
        ]
    ],
    "error": false
}
```

Ich hätte zwar gerne, dass die inneren Arrays im `choices` Array Objekte sind (Indexzahl als Key, Text als Value), aber das klappt nicht mit der `json_encode` Funktion und ist den signifikanten Mehraufwand zur Implementierung nicht wert.

@llgb Da sich mit Commit ee8ad55d7f8101fd7dbe61e54cfd83475289846f wie hier beschrieben das Format der JSON-Datei leicht geändert hat, muss der Javascript Teil angepasst werden. 

**EDIT:**
@llgb Vergiss es, wir wollten ja eh das UI neu machen und dynamisch alle verfügbaren Optionen abrufen und anzeigen, da muss es eh neu geschrieben werden, sorry ...
