### ISSUE TITLE
option-json.php liefert unvollständige Informationen zurück

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#43]
Bei Aufruf der URL `http://192.168.0.4/option-json.php?descriptor=%2Fmain%2Fstatus%2Fbatterylevel` kommt aktuell folgende JSON-Datei zurück:

``` javascript
{"option":"\/main\/status\/batterylevel","label":"Camera Status Information","type":"UNKNOWN","current":"","choices":[],"error":false}
```

Diese ist offensichtlich unvollständig. Stand: Aktueller Master. Dies passierte noch vor einigen Tagen so nicht.

**Comment by nsommer** [comment]
Scheinbar heißt die Konfigurationsoption des Akkustands bei unserer Referenzkamera anders, als bei deiner Spiegelreflex.

``` bash
gphoto2 --list-config | grep /main/status/batterylevel
```

Gibt kein Ergebnis. Nach einigem rumprobieren ergab sich, dass die Option zum Akkustand `/main/other/5001` heißt. Diese gibt folgende Ausgabe auf der Konsole.

``` bash
root@OpenWrt:~# gphoto2 --get-config /main/other/5001
Label: Battery Level                                                           
Type: MENU
Current: 100
Choice: 0 2
Choice: 1 5
Choice: 2 25
Choice: 3 50
Choice: 4 65
Choice: 5 80
Choice: 6 100
```

Ein entsprechender GET Request auf den richtigen descriptor funktioniert:

``` url
http://hostname/option-json.php?descriptor=%2Fmain%2Fother%2F5001
```

Die Response sieht so aus:

``` javascript
{"option":"\/main\/other\/5001","label":"Battery Level","type":"MENU","current":"100","choices":[],"error":false}
```

Label und current stimmen hier, jedoch ist das `choices` Array leer, was ein Fehler ist. Daher kann dieser Issue noch nicht geschlossen werden.

**Comment by nsommer** [comment]
Dass die Kameras unterschiedliche Identifier/Deskriptoren für die gleiche Option verwenden ist übrigens sehr bedenklich! Das macht es fast unmöglich, verschiedene Kameras zu unterstützen...

**Comment by llgb** [comment]
uuaah was ist denn das bitte für ein ****
Der Choices Array war bei mir für diesen Eintrag übrigens ebenfalls leer: 

> {"option":"\/main\/status\/batterylevel","label":"Battery Level","type":"TEXT","current":"40%","choices":[],"error":false} 

(Ich denke, dass dies bei allen "Einstellungen" ist, auf die der Anwender keinen direkten Einfluss hat)

on topic: 
ist auf jeden Fall shit, wie sollen wir weiter vorgehen?
Mein Vorschlag wäre (um die Referenzkamera und möglichst viele Spiegelreflexkameras abzudecken), dass wir vor der Abfrage des Batteriestatuses prüfen ob das _type_ Feld von `/main/status/batterylevel` == UNKNOW ist. Sollte dies der Fall sein wird `/main/other/5001` abgefragt.

Soll ich das mal so implementieren?

**Comment by nsommer** [comment]
> Der Choices Array war bei mir für diesen Eintrag übrigens ebenfalls leer:

Ich sehe gerade auch wieso: Bei der Instanziierung eines Option Objekts wird das choices Array nur dann gefüllt, wenn der `Type` `Radio` ist, beim Batterylevel ist der Type aber `MENU`. Ehrlich gesagt finde ich das auch in Ordnung so, denn es handelt sich ja eh um eine Option, die man nicht ändern kann/soll (der Akku läd sich ja nicht auf, nur weil man den Wert auf 100 setzt :D ).

> Mein Vorschlag wäre (um die Referenzkamera und möglichst viele Spiegelreflexkameras abzudecken), dass wir vor der Abfrage des Batteriestatuses prüfen ob das type Feld von /main/status/batterylevel == UNKNOW ist. Sollte dies der Fall sein wird /main/other/5001 abgefragt.
> 
> Soll ich das mal so implementieren?

Ja. Schreib am besten einen Kommentar zu der entsprechenden Stelle im Javascript, die das kurz erläutert.
