### ISSUE TITLE
Pfeilbuttons in Intervalleingabefeldern funktionieren nicht.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#44]
Drückt man den Pfeil-Hoch-Button an einem Eingabefeld im Intervalleinstellungstab, erscheint in dem Feld `NaN` (Not a Number).

Möglicherweise muss das `type` Attribut der input Elemente auf `number` gesetzt werden?

![bildschirmfoto 2015-04-17 um 14 19 18](https://cloud.githubusercontent.com/assets/5717791/7201906/0d837396-e50d-11e4-8124-00947410ea53.png)

**Comment by llgb** [comment]
Das muss eher am Kopieren/Auslagern der Elemente liegen.

> Möglicherweise muss das `type` Attribut der input Elemente auf `number` gesetzt werden?

Leider nein, das Attribut steht bewusst auf "text", da im Falle von `type="number"` innerhalb des input-Feldes Die Pfeile entstehen und unschön aussehen.
![screenshot](http://i.imgur.com/9P8DKC1.jpg)

Genau aus dem Grund musste ich den Weg mit den Javascript-Spinner-Buttons gehen.
Ich denke eher, dass er versucht den Feldinhalt als Zahl zu interpretieren und daran scheitert.
Kümmere mich aber direkt darum

**Comment by llgb** [comment]
gefixt mit 4cb006ad5de52cfde364e4e50b0f15ebfec2084d

Ich dachte eigentlich daran, in die Funktion zum verringern der Werte ncoh was einzubauen, damit die Werte nicht unter 0 gehen können.
Allerdings haben wir nicht in der Hand, dass der User das manuell einträgt. Deshalb würde ich vorschlagen, die Logik hierfür beim Auswerten der GET Parameter anzusiedeln.

**Comment by nsommer** [comment]
> Allerdings haben wir nicht in der Hand, dass der User das manuell einträgt.

Das ist immer so bei Eingaben in Weboberflächen. Sollte trotzdem auch clientseitig validiert werden. Serverseitige Validierung kommt natürlich dazu.

**Comment by llgb** [comment]
fixed with commit 7166e1e2c610eb1fd854d4b1ae09366ad58adbf9
