### ISSUE TITLE
Foto auf Indexsseite ist nicht das neueste

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#46]

**Comment by nsommer** [comment]
Sehr beunruhigend: Wie im Dateimanager und/oder per ssh zu sehen, existieren die heute geschossenen Fotos gar nicht. Das letzte Foto, das in `/www/photos` liegt, stammt vom 17.04.

Somit liegt das Problem nicht an der Sortierreihenfolge, sondern wo anders.

**Comment by llgb** [comment]
Oh man absolut dubios -.-
Ein kleiner Lichtblick ist ja, dass es bei mir auf dem Router funktioniert.
![Screenshot](http://i.imgur.com/YwpsAE2.jpg)
Aber das Downloaden der Bilder hat bei dir mit der Referenzkamera ja schon mal funktioniert, oder?
Immerhin können wir es so mal auf ein lokales Problem bei Dir eingrenzen

**Comment by nsommer** [comment]
Es geht ja meist bei mir auch und die Bilder müssen ja auch auf dem Router gewesen sein, sonst hätte man sie ja nicht anzeigen können. Ich tippe darauf, dass beim Neustart des Routers, als die Weboberfläche nicht mehr ansprechbar war, irgendwie das Dateisystem die Dateien verloren hat.

**Comment by llgb** [comment]
ok das klingt schlüssig.
Hast Du schon mal geschaut ob Du das hotplug package installiert hast?
Bei mir sind folgende Pakete installiert: http://pastebin.com/vcG7HwLk
