### ISSUE TITLE
Oberstes horizontales Menü nicht responsive.

### ISSUE THREAD

**Issue by nsommer** [StudA-EPR/EPR-CRC#47]

**Comment by llgb** [comment]
Irgendwas stimmt bei deiner Kiste nicht, bei mir zeigt es das Menü oben responsive an:
![](http://i.imgur.com/YvOt90u.jpg)
@nsommer Löscht dir vielleicht das deployskript Dinge die benötigt werden, oder kopiert vielleicht nicht alle Files?

**Comment by nsommer** [comment]
Bei mir nicht, aktueller Master.

![img_20150421_212904](https://cloud.githubusercontent.com/assets/5717791/7260881/c4dcbe9a-e86d-11e4-8946-6036b287b57c.png)

Bei mir werden alle Dateien mit Endung `.js` im Ordner `www/js/` und alle Dateien mit Endung `.css` im Ordner `www/css/` deployt, von den Assets müsste also alles da sein.

**Comment by llgb** [comment]
wie geht denn das :confused: 
folglich bekommst du auch beim Skalieren deine Browserfensters kein responsives Menü.
Die entsprechenden .js und .css Dateien sind bei Dir aber auf dem Router, oder?

**Comment by nsommer** [comment]
> Die entsprechenden .js und .css Dateien sind bei Dir aber auf dem Router, oder?

Klar, würde man ja auch sehen weil die ganzen Bootstrap Styles fehlen würden.

> folglich bekommst du auch beim Skalieren deine Browserfensters kein responsives Menü.

Interessant, dass du's ansprichst. Ich hab es gerade mal probiert. Das Fenster im ersten Screenshot ist etwas breiter als das im zeiten. 

![bildschirmfoto 2015-04-21 um 21 41 03](https://cloud.githubusercontent.com/assets/5717791/7261105/705dfd00-e86f-11e4-8761-acfafdf35dc6.png)
![bildschirmfoto 2015-04-21 um 21 41 12](https://cloud.githubusercontent.com/assets/5717791/7261106/70839416-e86f-11e4-9fd8-e4ddbce5f681.png)

Das heißt auf dem Notebook funktioniert es. Dann baut wohl mein BlackBerry Mist. Aber ich habe da schon so oft Seiten mit diesem Bootstrap Menü angesehen und es klappte immer bisher.

Was mir aber dazu noch einfällt. Ich glaube du hast das Menü falsch benutzt. Das ist auch in der Breite begrenzt, statt von ganz links bis ganz rechts zu gehen. Könnte mir gut vorstellen, dass es daran liegt.

**Comment by llgb** [comment]
> Das heißt auf dem Notebook funktioniert es. Dann baut wohl mein BlackBerry Mist. Aber ich habe da schon so oft Seiten mit diesem Bootstrap Menü angesehen und es klappte immer bisher.

Eigentlich ja, was aber dagegen spricht ist, dass es die Seite mit meinem Smartphone und deinem Router auch falsch dargestellt hat. Hier zuhause mit meinem Router hat mein Smartphone das Menü allerdings korrekt dargestellt. Dies dürfte ja eigentlich nicht sein, da sowohl dein als auch mein Router auf dem selben Stand waren.

> Was mir aber dazu noch einfällt. Ich glaube du hast das Menü falsch benutzt. Das ist auch in der Breite begrenzt, statt von ganz links bis ganz rechts zu gehen. Könnte mir gut vorstellen, dass es daran liegt.

Oh das ist falsch? Ich dachte eigentlich das wäre beabsichtigt, weil dann die Breite des Menüs (im nicht responsiven Zustand) dann auch nur so breit wie der Inhalt unten ist. Also stelle ich mir optisch ansprechender vor als wenn das Menü oben über die komplette Breite geht :D
Ich kann das aber nachher mal umstellen dann versuchst du es nochmal auf dem Blackberry

**Comment by nsommer** [comment]
> Eigentlich ja, was aber dagegen spricht ist, dass es die Seite mit meinem Smartphone und deinem Router auch falsch dargestellt hat. Hier zuhause mit meinem Router hat mein Smartphone das Menü allerdings korrekt dargestellt. Dies dürfte ja eigentlich nicht sein, da sowohl dein als auch mein Router auf dem selben Stand waren.

Achso, das hab ich nicht mitgekriegt. Das ist ganz schön komisch ...

**Comment by llgb** [comment]
> Was mir aber dazu noch einfällt. Ich glaube du hast das Menü falsch benutzt. Das ist auch in der Breite begrenzt, statt von ganz links bis ganz rechts zu gehen. Könnte mir gut vorstellen, dass es daran liegt.

Habe jetzt nochmal auf der Bootstrap Seite geschaut, dort ist es meiner Meinung nach gleich umgesetzt wie bei uns:
http://getbootstrap.com/examples/navbar/
Kannst Du mal schauen ob Dein Blackberry die Seite richtig anzeigt?

**Comment by nsommer** [comment]
> Habe jetzt nochmal auf der Bootstrap Seite geschaut, dort ist es meiner Meinung nach gleich umgesetzt wie bei uns:

Ah, ich verwende es immer so: [http://getbootstrap.com/examples/navbar-static-top/](http://getbootstrap.com/examples/navbar-static-top/) Finde ich persönlich optisch besser. Aber mir ist das relativ egal, lass es ruhig so wie es ist. Ich dachte bloß da wäre vielleicht ein Fehler, weil ich das bisher so noch nicht gesehen hab.

> Kannst Du mal schauen ob Dein Blackberry die Seite richtig anzeigt?

Jap, tut es.

**Comment by llgb** [comment]
> Ah, ich verwende es immer so: http://getbootstrap.com/examples/navbar-static-top/ Finde ich persönlich optisch besser. Aber mir ist das relativ egal, lass es ruhig so wie es ist. Ich dachte bloß da wäre vielleicht ein Fehler, weil ich das bisher so noch nicht gesehen hab.

achsoo ok. Also klar ändern wäre auch jederzeit möglich, aber zumindest schaut es so aus als wäre die aktuelle Implementierung auch gültig.

Kurios ist es trotzdem. Ich teste morgen die Router-Seite mal noch mit dem iPhone meiner Freundin.

**Comment by nsommer** [comment]
Scheint entweder ein Problem meines Handys oder meines Routers zu sein.
