### ISSUE TITLE
Optionen werden nicht richtig in <select> Box angezeigt

### ISSUE THREAD

**Issue by llgb** [StudA-EPR/EPR-CRC#48]
Die dynamisch erstellten Selectboxen werden nicht korrekt mit den Werten der Optionen befüllt
![fehleroptions](https://cloud.githubusercontent.com/assets/5757757/7279483/a2dd2884-e91c-11e4-9b3e-26b7e7df09db.JPG)

Wie man im Screenshot sehen kann, sieht es auf den ersten Blick nach einem Regex Problem aus.
Optionen vom Typ "TEXT" werden korrekt dargestellt.

Der Parameter "Shutterspeed2" (/main/capturesettings/shutterspeed2) wird im Quelltext wie folgt erstellt;

```
<select id="/main/capturesettings/shutterspeed2" class="form-control" name="/main/capturesettings/shutterspeed2">
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">/</option>
<option value="1">0</option>
<option value="1">/</option>
<option value="1">0</option>
<option value="1">0</option>
<option value="1">undefined</option>
<option value="1">3</option>
<option value="1">6</option>
<option value="2">undefined</option>
<option value="2">5</option>
<option value="3">undefined</option>
<option value="4">undefined</option>
<option value="5">undefined</option>
<option value="6">undefined</option>
<option value="8">undefined</option>
<option value="1">0</option>
<option value="1">3</option>
<option value="1">5</option>
<option value="2">0</option>
<option value="2">5</option>
<option value="3">0</option>
```

(ebenfalls zu beachten die "value" Werte)

**Comment by nsommer** [comment]
Könntest du mir hier mal die Ausgaben von `gphoto2 --get-config <identifier>` für die zwei von dir genannten Beispiele posten? Dann kann ich mal durchdebuggen ...

**Comment by llgb** [comment]
Ausgabe für **/main/settings/imagecommentenable**

```
root@OpenWrt:~# gphoto2 --get-config /main/settings/imagecommentenable
Label: Enable Image Comment
Type: RADIO
Current: Off
Choice: 0 On
Choice: 1 Off
```

Ausgabe für: **/main/capturesettings/shutterspeed2**

```
root@OpenWrt:~# gphoto2 --get-config /main/capturesettings/shutterspeed2
Label: Shutter Speed 2
Type: RADIO
Current: 25
Choice: 0 1/4000
Choice: 1 1/3200
Choice: 2 1/2500
Choice: 3 1/2000
Choice: 4 1/1600
Choice: 5 1/1250
Choice: 6 1/1000
Choice: 7 1/800
Choice: 8 1/640
Choice: 9 1/500
Choice: 10 1/400
Choice: 11 1/320
Choice: 12 1/250
Choice: 13 1/200
Choice: 14 1/160
Choice: 15 1/125
Choice: 16 1/100
Choice: 17 1/80
Choice: 18 1/60
Choice: 19 1/50
Choice: 20 1/40
Choice: 21 1/30
Choice: 22 1/25
Choice: 23 1/20
Choice: 24 1/15
Choice: 25 1/13
Choice: 26 1/10
Choice: 27 1/8
Choice: 28 1/6
Choice: 29 1/5
Choice: 30 1/4
Choice: 31 1/3
Choice: 32 10/25
Choice: 33 1/2
Choice: 34 10/16
Choice: 35 10/13
Choice: 36 1
Choice: 37 13/10
Choice: 38 16/10
Choice: 39 2
Choice: 40 25/10
Choice: 41 3
Choice: 42 4
Choice: 43 5
Choice: 44 6
Choice: 45 8
Choice: 46 10
Choice: 47 13
Choice: 48 15
Choice: 49 20
Choice: 50 25
Choice: 51 30
```

Die select-Optionen für die shutterspeed Einstellung stehen im vorherigen Post.
Die für das Beispiel `/main/settings/imagecommentenable` sehen so aus:

```
<select id="/main/settings/imagecommentenable" class="form-control" name="/main/settings/imagecommentenable">
<option value="O">n</option>
<option value="O">f</option>
</select>
```

**Comment by nsommer** [comment]
Danke! Ich habe mal eben ein Testskript geschrieben. Die Option Klasse scheint aber alles richtig zu machen, es parst korrekt bei mir.

Ich schau jetzt mal ob im Javascript Teil irgendwas schief läuft.

**Comment by nsommer** [comment]
Gib mir mal bitte noch die Ergebnisse der Requests `GET /option-json.php?descriptor=%2Fmain%2Fsettings%2Fimagecommentenable` und `GET /option-json.php?descriptor=%2Fmain%2Fcapturesettings%2Fshutterspeed2`. @llgb

**Comment by nsommer** [comment]
Also ich habe gerade lokal aus den von dir geposteten gphoto Ausgaben Option Klassen instanziiert, mittels json_encode() enkodiert und das JSON Objekt in der Entwicklerkonsole des Browsers der buildUIElementsForOption() Funktion übergeben. Diese hat das Select-Feld absolut korrekt aufgebaut.

Siehe Screenshots:

![bildschirmfoto 2015-04-25 um 21 38 36](https://cloud.githubusercontent.com/assets/5717791/7334469/8bc91aa8-eb93-11e4-98f9-b2bfdc0c4253.png)
![bildschirmfoto 2015-04-25 um 21 38 56](https://cloud.githubusercontent.com/assets/5717791/7334471/906eb2f2-eb93-11e4-9329-0fd6fecf4e49.png)

@llgb Bist du ganz sicher, dass du auf dem aktuellen Master bist und dass du alle Dateien korrekt deploy t hast?

**Comment by llgb** [comment]
> @llgb Bist du ganz sicher, dass du auf dem aktuellen Master bist und dass du alle Dateien korrekt deploy t hast?

oO so ein shit, was ist denn da los. Auf dem aktuellen Master bin ich. Werde zur Sicherheit jetzt nochmal das gesamte Verzeichnis rüber kopieren und alles überschreiben.
Sollte das Problem dann noch bestehen gebe ich Dir die JSON Ausgaben

**Comment by llgb** [comment]
Oh man Nils, tut mir tierisch leid. Ich schiebe immer nach dem pullen die geänderten Dateien rüber, aber anscheinend ist da entweder was durchgerutscht oder wurde nicht von der neuen Datei überschrieben. Jetzt nachdem vollständigen sauberen neu-deployen  tut es so wie es soll und füllt die Boxen korrekt.
![options](https://cloud.githubusercontent.com/assets/5757757/7334700/c0149baa-eb9a-11e4-94e7-344dcb03e70a.JPG)
Sorry, dass ich da deine Zeit beansprucht hab obwohl es schon funktioniert hat.

**Comment by nsommer** [comment]
Shit happens ^^
